print("First Time Stamp")
a = int(input("Enter Hours: "))
b = int(input("Enter Minutes: "))
c = int(input("Enter Seconds: "))
print("Second Time Stamp")
d = int(input("Enter Hours: "))
e = int(input("Enter Minutes: "))
f = int(input("Enter Seconds: "))
g = int(a)*3600 + int(b)*60 + int(c)
h = int(d)*3600 + int(e)*60 + int(f)
i = int(g) - int(h)
print(i)
